package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import userclasses.StateMachine;
import com.codename1.io.Log;
import com.codename1.ui.Font;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
   
    private Form current;
        private Resources theme;

    public void init(Object context) {
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
            
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
         theme = UIManager.initFirstTheme("/theme");
        Login login = new Login();
         login.getTitleArea().setHidden(true);
       // login.getAllStyles().setBgColor(000000);
       login.gui_Span_Label.getTextAllStyles().setFont(Font.createSystemFont(Font.FACE_SYSTEM, Font.STYLE_BOLD, Font.SIZE_SMALL));
       login.gui_Span_Label.getTextAllStyles().setFgColor(0xffffff);
       login.gui_TextField.getAllStyles().setBgColor(0xffffff);
       login.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }
}
